apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: javaapptest
  namespace: sumit
spec:
  schedule: "*/5 * * * *"       
  concurrencyPolicy: "Replace"  
  startingDeadlineSeconds: 200  
  suspend: false                
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1     
  jobTemplate:                  
    spec:
      template:
        metadata:
          labels:               
            parent: "cronjobpi"
        spec:
          containers:
          - name: javaapp
            image: praveenlti/javaapp1:latest
            #command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: OnFailure 
